# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWY4NGI2NGUwMmU1NmU1ODY2NmU1ZTQ4ZWFhMmNjYmI4ZjYyM2MyZWEyM2YwNGVmM2ZjNmI4YWZmYzc1NmE4OWZhMzZhMDI4OTBiNjc0MDNlM2UxN2ExMzc5YzJkMjlkNzBkNjE5MTI1NmVhNGM0OGQ2OTVjOWVjM2JkYWIzMTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
